config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do 
      resources :messages, only: :index, defaults: { format: 'json' } #defaultsオプションを利用して、このルーティングが来たらjson形式でレスポンスするよう指定。
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :messages
  has_many :users, through: :group_users

  validates :name, presence: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id]) #今いるグループの情報をパラムスの値を元にDBから取得。
    @messages = @group.messages.includes(:user).where('id > ?', params[:last_id]) #グループが所有しているメッセージの中から、params[:last_id]よりも大きいidがないかMessageから検索して、@messagesに代入。
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html{ redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

# class MessagesController < ApplicationController
#   before_action :set_group

#   def index
#     @message = Message.new
#     @messages = @group.messages.includes(:user)
#   end

#   def create
#     @message = @group.messages.new(message_params)
#     if @message.save
#       redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'
#     else
#       @messages = @group.messages.includes(:user)
#       flash.now[:alert] = 'メッセージを入力してください。'
#       render :index
#     end
#   end

#   private

#   def message_params
#     params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
#   end

#   def set_group
#     @group = Group.find(params[:group_id])
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?) and id != ?', "%#{params[:keyword]}%" ,current_user)
    respond_to do |format|  
      format.html
      format.json
   end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :user_id)
  end
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message

  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :users, "チャットメンバーを追加", class: 'chat-group-form__label', for:'user-search-field'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :users, id: 'user-search-field', class: 'chat-group-form__input', value: '', placeholder: '追加したいユーザー名を入力してください'
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :user_ids, "チャットメンバー", class: 'chat-group-form__label'

    .chat-group-form__field--right
      #chat-group-users
        - @group.users.each do |user|
          .chat-group-user.clearfix.js-chat-member{data: {id: user.id}}
            %input{name: 'group[user_ids][]', type: 'hidden', value: "#{ user.id }"}
            %p.chat-group-user__name
              = user.name
              - if user != current_user
                %p.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除 
              - else
                %p.none

      #member_search_result
  .chat-group-form__field.clearfix 
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/index.html.haml
.wrapper

  = render 'messages/side_bar'
 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/notifications'
    /= render partial: 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.message{"data-message-id": "#{message.id}"}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  .lower-meesage
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'
  .groups
    .group
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/messages/index.html.haml
.wrapper
  = render 'side_bar'
  .chat
    .header
      .left-header
        .left-header__title
          = @group.name
        %ul.left-header__members
          Member：
          %li.member
          - @group.users.each do |member|
            = member.name
      .right-header
        .right-header__button
          =link_to edit_group_path(@group) do
            Edit
    .messages
      = render @messages
      
    .form
      = form_for [@group, @message], id: "new_message" do |f|
        = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        .form__mask
          = f.label :image, class: 'form__mask__image' do
            = fa_icon 'picture-o', class: 'icon'
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'